# Generated by Django 2.1.3 on 2019-01-26 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentOutAHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_area', models.IntegerField(blank=True)),
                ('number_of_rooms', models.SmallIntegerField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True)),
                ('finale_date', models.DateField(blank=True)),
                ('identity_docs', models.ImageField(blank=True, upload_to='')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('cost_per_day', models.FloatField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('family', models.CharField(max_length=30)),
            ],
        ),
    ]
